#!/usr/bin/env python

from netaddr import *
import re
import argparse

def is_found(line, addr, isCIDR):
	# get ip string at each line if available
	ip_str = re.search(r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}', line).group(0)
	if ip_str != "":
		ip = IPAddress(ip_str)
		if isCIDR:
			return ip in addr
		return ip == addr
	return False
	pass

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description='Parse log file with IP/CIDR address')
	parser.add_argument('--ip', metavar='IP', type=str, help='an IP address or CIDR block', required=True)
	parser.add_argument('--file', metavar='LOG FILE', type=str, help='file location', required=True)
	args = parser.parse_args()
	input_str = args.ip
	file_name = args.file

	# check if the string is CIDR or IP
	if input_str.find('/'):
		addr = IPNetwork(input_str)
		isCIDR = True
	else:
		addr = IPAddress(input_str)
		isCIDR = False

	open('output.txt', 'w') .writelines([ line for line in open(file_name) if is_found(line, addr, isCIDR) ])
	pass

  
  
